--------------------------------------------------------------------------------
-- #267: Bad exception catching
--------------------------------------------------------------------------------

pcall inside xpcall:	true	pcall is ok
pcall with Lua error():	false	some message
pcall with db.error():	false	Illegal parameters, some message
pcall with no return:	1
pcall with multireturn:	true	1	2	3
